version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - MONITORING_INTERVAL=300
      - MAX_POSITION_SIZE=1000
      - RISK_PER_TRADE=0.02
      - MAX_DAILY_TRADES=10
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: 