services:
  # Backend API Service
  - type: web
    name: nostrade-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: MONITORING_INTERVAL
        value: 300
      - key: MAX_POSITION_SIZE
        value: 1000
      - key: RISK_PER_TRADE
        value: 0.02
      - key: MAX_DAILY_TRADES
        value: 10
    healthCheckPath: /
    autoDeploy: true

  # Frontend Dashboard
  - type: web
    name: nostrade-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://nostrade-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    autoDeploy: true 